- hosts: server1  
  remote_user: dr
  become: yes  
  tasks:

    - name: Install packages
      apt: name= state=present
      with_items:
          - qemu-kvm
          - libvirt-clients
          - libvirt-daemon-system
          - bridge-utils
          - virt-manager


    - name: Create network config file
      file:
        path: /etc/network/interfaces
        state: touch
        mode: u=rw,g=rw,o=rw

    - name: Adding configuration for network interfaces        
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto br0

          iface eth0 inet manual

          iface br0 inet dhcp
            bridge_ports eth0

    - name: Ensure group "libvirt" exists
      group:
        name: libvirt
        state: present

    - name: Ensure group "libvirt-qemu" exists
      group:
        name: libvirt-qemu
        state: present

    - name: Updating user
      user: name=dr
            state=present
            groups="libvirt, libvirt-qemu"
            comment="Adding groups to user"
    